-- ─────────────────────────────────────────
-- V3 — run in Supabase SQL Editor
-- Adds hubspot_audience column + bulk inserts 2026 show calendar
-- ─────────────────────────────────────────

ALTER TABLE shows ADD COLUMN IF NOT EXISTS hubspot_audience text[] DEFAULT '{}';

-- Update the existing Bendigo May show
UPDATE shows
SET hubspot_audience = ARRAY['VIC Leads'], site_number = 'R5 & R6'
WHERE start_date = '2026-05-29' AND end_date = '2026-05-31';

-- Insert all 2026 shows (skip Bendigo May which already exists)
INSERT INTO shows (name, start_date, end_date, location, site_number, brands, website_url, hubspot_audience) VALUES

('Geelong Outdoor Living & Caravan Expo',       '2026-01-16', '2026-01-18', 'Geelong, VIC',              NULL,                                          ARRAY[]::text[],                              'https://www.outdoorlivingcaravanexpo.com.au/geelong/',                                  ARRAY['VIC Leads']),
('OTRV Yard Sale',                              '2026-01-30', '2026-02-01', 'Off Track RV, Dandenong VIC', NULL,                                         ARRAY['Vacationer','Radiant','Atlas','OzVenture'], 'https://www.offtrackrv.com.au/',                                                        ARRAY['All Marketing Contacts']),
('Wagga Wagga Caravan & Camping Show',          '2026-02-06', '2026-02-08', 'Wagga Wagga, NSW',          NULL,                                          ARRAY[]::text[],                              'https://www.caravanshow.com.au/',                                                       ARRAY['NSW Leads']),
('Melbourne Caravan & Camping Show',            '2026-02-18', '2026-02-22', 'Melbourne Showgrounds, VIC', NULL,                                          ARRAY[]::text[],                              'https://www.caravanshow.com.au/',                                                       ARRAY['VIC Leads']),
('Orange Outdoor Living & Caravan Expo',        '2026-02-27', '2026-03-01', 'Orange, NSW',               NULL,                                          ARRAY[]::text[],                              'https://www.outdoorlivingcaravanexpo.com.au/orange/',                                   ARRAY['NSW Leads']),
('Mornington Outdoor Living & Caravan Expo',    '2026-03-13', '2026-03-15', 'Mornington, VIC',           '132, 133, 134',                               ARRAY['Vacationer','Radiant','Atlas'],         'https://www.outdoorlivingcaravanexpo.com.au/mornington/',                               ARRAY['VIC Leads']),
('Perth Caravan & Camping Show',                '2026-03-19', '2026-03-22', 'Perth, WA',                 '628, 630, 631, 518-520',                      ARRAY['Vacationer','Radiant','Atlas'],         'https://caravanwa.com.au/perth-caravan-camping-show/',                                  ARRAY['WA Leads','SA Leads']),
('Border Caravan & Camping Leisurefest',        '2026-03-27', '2026-03-29', 'Albury-Wodonga, VIC/NSW',   'Atlas: B12, Vacationer: C12, Radiant: C16',   ARRAY['Vacationer','Radiant','Atlas'],         'https://www.caravanshow.com.au/shows/the-border-caravan-camping-leisurefest/',          ARRAY['VIC Leads','NSW Leads']),
('Ballarat Outdoor Living & Caravan Expo',      '2026-04-10', '2026-04-12', 'Ballarat, VIC',             '40, 41, 43 & 44',                             ARRAY['Vacationer','Radiant','Atlas'],         'https://www.outdoorlivingcaravanexpo.com.au/ballarat/',                                 ARRAY['VIC Leads']),
('Cranbourne Caravanning & Adventure Leisurefest','2026-05-08','2026-05-10','Cranbourne, VIC',            'A20 Radiant, A22 Atlas, C01 Vacationer',       ARRAY['Vacationer','Radiant','Atlas'],         'https://www.caravanshow.com.au/shows/cranbourne-caravanning-adventure-leisurefest/',    ARRAY['VIC Leads']),
('Hunter Valley Outdoor Show',                  '2026-05-22', '2026-05-24', 'Hunter Valley, NSW',        '260 (Radiant), 265, 266 (Vacationer)',         ARRAY['Vacationer','Radiant'],                 'https://www.ruralscene.com.au/',                                                        ARRAY['NSW Leads']),
('OTRV Yard Sale',                              '2026-06-05', '2026-06-07', 'Off Track RV, Dandenong VIC', 'Hours: 9am-5pm',                            ARRAY['Vacationer','Radiant','Atlas','OzVenture'], 'https://www.offtrackrv.com.au/',                                                        ARRAY['VIC Leads']),
('Bathurst 4WD & Outdoor Show',                 '2026-09-04', '2026-09-06', 'Bathurst, NSW',             NULL,                                          ARRAY['Vacationer','Radiant'],                 'https://sydney.4wdshow.com.au/',                                                        ARRAY['NSW Leads']),
('Albury Wodonga Caravan & Outdoor Show',       '2026-09-04', '2026-09-06', 'Albury, VIC/NSW',           NULL,                                          ARRAY['Vacationer','Radiant','Atlas'],         'https://www.ruralscene.com.au/',                                                        ARRAY['VIC Leads','NSW Leads']),
('Wauchope Caravan & Outdoor Show',             '2026-07-08', '2026-07-10', 'Wauchope, NSW',             NULL,                                          ARRAY['Vacationer','Radiant'],                 'https://www.ruralscene.com.au/',                                                        ARRAY['NSW Leads']),
('Greater Sydney Caravan & Outdoor Leisure Roadshow','2026-07-24','2026-07-26','Sydney, NSW',            NULL,                                          ARRAY[]::text[],                              'https://caravanroadshows.com.au/greater-sydney-caravan-roadshow/',                     ARRAY['NSW Leads']),
('Shepparton Outdoor Living & Caravan Expo',    '2026-08-14', '2026-08-16', 'Shepparton, VIC',           NULL,                                          ARRAY['Vacationer','Radiant','Atlas'],         'https://www.outdoorlivingcaravanexpo.com.au/',                                          ARRAY['VIC Leads']),
('Sydney 4x4 & Outdoor Show',                   '2026-09-09', '2026-09-13', 'Sydney Olympic Park, NSW',  NULL,                                          ARRAY['Vacationer','Radiant'],                 'https://sydney.4wdshow.com.au/',                                                        ARRAY['NSW Leads']),
('Sandown Melbourne Leisurefest',               '2026-09-17', '2026-09-20', 'Sandown Racecourse, VIC',   NULL,                                          ARRAY[]::text[],                              'https://melbourneleisurefest.com.au/',                                                  ARRAY['VIC Leads']),
('Lake Macquarie Caravan & Camping Show',       '2026-09-11', '2026-09-13', 'Lake Macquarie, NSW',       NULL,                                          ARRAY[]::text[],                              'https://www.caravanshow.com.au/',                                                       ARRAY['NSW Leads']),
('Perth 4x4 & Outdoor Show',                    '2026-09-11', '2026-09-13', 'Perth, WA',                 NULL,                                          ARRAY[]::text[],                              'https://4wdshow.com.au/',                                                               ARRAY['WA Leads']),
('Mandurah Show',                               '2026-10-10', '2026-10-12', 'Mandurah, WA',              NULL,                                          ARRAY[]::text[],                              'https://mandurah.show/',                                                                ARRAY['WA Leads']),
('Traralgon Outdoor Living & Caravan Expo',     '2026-10-17', '2026-10-19', 'Traralgon, VIC',            NULL,                                          ARRAY[]::text[],                              'https://www.outdoorlivingcaravanexpo.com.au/',                                          ARRAY['VIC Leads']),
('Canberra Caravan & Camping Expo',             '2026-10-24', '2026-10-26', 'Canberra, ACT',             NULL,                                          ARRAY[]::text[],                              'https://caravanexpo.com.au/',                                                           ARRAY['ACT Leads','NSW Leads']),
('Bendigo Outdoor Living & Caravan Expo',       '2026-11-21', '2026-11-23', 'Bendigo, VIC',              NULL,                                          ARRAY[]::text[],                              'https://www.outdoorlivingcaravanexpo.com.au/',                                          ARRAY['VIC Leads']),
('Geelong Outdoor Living & Caravan Expo',       '2026-11-28', '2026-11-30', 'Geelong, VIC',              NULL,                                          ARRAY[]::text[],                              'https://www.caravanshow.com.au/',                                                       ARRAY['VIC Leads']),
('Batemans Bay Caravan & Outdoor Leisure Roadshow','2026-05-12','2026-05-14','Batemans Bay, NSW',         NULL,                                          ARRAY[]::text[],                              'https://caravanroadshows.com.au/batemans-bay-caravan-outdoor-leisure-roadshow/',        ARRAY['NSW Leads'])
;
